### ISSUE TITLE
crash going from 1.0.5 to 1.1.0, fatal error use of unimplemented initializer 'init()' for class

### ISSUE THREAD

**Issue by ghost** [yonat/SweeterSwift#1]
**Description of the problem:**
[description]
weird crashes in working code after going from 1.0.5 to 1.1.0
-- e.g. crash in a class, fatal error use of unimplemented initializer 'init()' for class

Verified that it's this pod. going back to 1.0.5 on a single pod fixes issues. There were no code changes between - just updates on the pod.

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
[github repo or a zipped project]

This class worked fine before:

class MyThread: Thread {
init(param1: Int = 1, param2 : Int = 1) {
  super.init()
  // init code
}

final override func main() {
   // do stuff
}
}

calling this in appDelegate as let t = MyThread() causes the crash. 
fatal error use of unimplemented initializer 'init()' for class MyThread

**Comment by ghost** [comment]
Another piece of info - I'm actually using multi slider, the SweeterSwift dependency is from there.

**Comment by yonat** [comment]
What happens if you implement `override init()` in addition to your init?

**Comment by ghost** [comment]
it works for that class, but there are other classes that throw the same error and these come from third party pods that i have no control on. These worked before... weird, right?

**Comment by yonat** [comment]
Sorry about that, just pushed a fix. Please try:

```
$ pod repo update
$ pod update "SweeterSwift"
```

**Comment by ghost** [comment]
That fixed it! Thanks for the quick fix :-) Cheers!
