### ISSUE TITLE
Build error when import with SPM

### ISSUE THREAD

**Issue by naivalf27** [yonat/SweeterSwift#3]
When import with lib: [MultiSlider](https://github.com/yonat/MultiSlider) with SPM
Error in file : UITextView+Sweeter.swift :
- 'labelFontSize' is unavailable in tvOS
- 'isEditable' is unavailable in tvOS
- 'dataDetectorTypes' is unavailable in tvOS

used version : 1.1.2
target: only iOS

**Comment by yonat** [comment]
That's a weird and erroneous error by Xcode, since the code clearly states that the function is only available for iOS.

Fortunately, it doesn't stop the app from building and running.
