### ISSUE TITLE
Runtime error upon startup on iOS 14 devices when compiled with Xcode 13.3+

### ISSUE THREAD

**Issue by lukemmtt** [yonat/SweeterSwift#7]
(Copied from https://github.com/yonat/MultiSelectSegmentedControl/issues/50 for reference)

**Description of the problem:**
This module has been very helpful for me and my project, but starting with Xcode 13.3, I began receiving many reports from iOS 14 users stating that my app had begun crashing immediately at startup, and this module has been identified as the culprit. More specifically, the issue is in the SweeterSwift dependency which this package relies on.

My colleague forked the SweeterSwift package to devise a workaround here: https://github.com/zabolotiny/SweeterSwift

Similarly, I can see another fork of this dependency has been created by another user ( @Janek-CL ) that claims to fix the issue in a different way: https://github.com/CONVELOP-GbR/SweeterSwift

**Comment by yonat** [comment]
Fixed by tylerjames in SweeterSwift 1.2.1 .
